FizzleBizzle/Models/FizzleBizzleModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace FizzleBizzle
{
    public interface IFizzleBizzle
    {
        int Fizz { set; get; }
        int Buzz { set; get; }

        //string[] FizzBuzz(int start, int end);

        string[] FizzBuzzBazz(int start, int end, Predicate<int> bazz);
    }

    public class FizzleBizzleModel : IFizzleBizzle
    {
        private int _fizz;
        private int _buzz;

        [Required]
        public int Fizz
        {
            get { return _fizz; }
            set { _fizz = value; }
        }

        [Required]
        public int Buzz
        {
            get { return _buzz; }
            set { _buzz = value; }
        }
        //------ Consolidate this into FizzBuzzBazz()
        //public string[] FizzBuzz(int start, int end)
        //{
        //    List<string> numList = new List<string>();

        //    for(int i = start; i <= end; i++)
        //    {
        //        if(i % Fizz == 0 && i % Buzz == 0)
        //        {
        //            numList.Add("FizzBuzz");
        //        } else if(i % Fizz == 0)
        //        {
        //            numList.Add("Fizz");
        //        } else if(i % Buzz == 0)
        //        {
        //            numList.Add("Buzz");
        //        } else
        //        {
        //            numList.Add(i.ToString());
        //        }
        //    }
        //    return numList.ToArray();
        //}

        public string[] FizzBuzzBazz(int start, int end, Predicate<int> bazz)
        {
            List<string> numList = new List<string>();

            for (int i = start; i <= end; i++)
            {
                var boolean = false;
                if (!bazz.Equals(null))
                    boolean = bazz(i);

                if (i % Fizz == 0 && i % Buzz == 0 && boolean)
                {
                    numList.Add("FizzBuzzBazz");
                }
                else if(i % Fizz == 0 && i % Buzz == 0) {
                    numList.Add("FizzBuzz");
                }
                else if (i % Fizz == 0)
                {
                    numList.Add("Fizz");
                }
                else if (i % Buzz == 0)
                {
                    numList.Add("Buzz");
                }
                else
                {
                    numList.Add(i.ToString());
                }
            }
            string[] list = numList.ToArray();
            return list;
        }
    }
}

FizzleBizzle/Controllers/FizzleBizzleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FizzleBizzle.Controllers
{
    public class FizzleBizzleController : Controller
    {
        [HttpGet]
        public ActionResult Index()
        {
            return View(new FizzleBizzleModel());
        }
        

        [HttpPost]
        public ActionResult FizzBuzzBazz(int start, int end, int fizz, int buzz, int? bazz, string type)
        {
            FizzleBizzleModel FizzBizz = new FizzleBizzleModel();
            FizzBizz.Fizz = fizz;
            FizzBizz.Buzz = buzz;
            if (ModelState.IsValid)
            {
                if (bazz != null)
                {
                    Predicate<int> pred = (x => x == 0);
                    switch (type)
                    {
                        case "gt":
                            pred = (x => x > bazz);
                            break;
                        case "lt":
                            pred = (x => x < bazz);
                            break;
                        case "eq":
                            pred = (x => x == bazz);
                            break;
                    }
                    ViewBag.Result = FizzBizz.FizzBuzzBazz(start, end, pred);
                }
                else
                {
                    Predicate<int> pred = null;
                    ViewBag.Result = FizzBizz.FizzBuzzBazz(start, end, pred);
                }
            }
            return PartialView("Results");
        }
    }
}

FizzleBizzle/Views/FizzleBizzle/FizzBuzzBazz.cshtml
<form id="fbForm" name="fbForm">
    <div class="col-xs-12 col-sm-6 fb-input">
        <input type="number" name="start" placeholder="Start" class="form-control" value="" required />
    </div>
    <div class="col-xs-12 col-sm-6 fb-input">
        <input type="number" name="end" placeholder="End" class="form-control" value="" required />
    </div>
    <div class="col-xs-12 col-sm-6 fb-input">
        <input type="number" name="fizz" placeholder="Fizz" class="form-control" value="" required />
    </div>
    <div class="col-xs-12 col-sm-6 fb-input">
        <input type="number" name="buzz" placeholder="Buzz" class="form-control" value="" required />
    </div>
    <div class="col-xs-12 col-sm-6 fb-input checkbox">
        <input type="checkbox" id="togBazz" data-toggle="toggle" data-onstyle="default" /><label for="togBazz" style="padding-left:5px;">Enable Bazz?</label>
    </div>
    <div class="col-xs-12 col-sm-6 fb-input bazz">
        <input type="number" name="bazz" placeholder="Bazz" class="form-control" value="" />
    </div>
    <div class="col-xs-12 col-sm-6 fb-input bazz">
        <select class="form-control" name="type">
            <option value="" disabled selected>Predicate</option>
            <option value="gt">Greater Than</option>
            <option value="lt">Less Than</option>
            <option value="eq">Equal To</option>
        </select>
    </div>
    <div class="col-xs-12 fb-btn-container">
        <button type="button" id="generate" class="fb-btn">Generate</button>
    </div>
</form>
<script type="text/javascript">
    $(document).ready(function () {
        $("#generate").on("click", function (e) {
            e.preventDefault();
            var form = $('#fbForm');
            var start = $('input[name=start]').val();
            var end = $('input[name=end]').val();
            var fizz = $('input[name=fizz]').val();
            var buzz = $('input[name=buzz]').val();
            var bazzToggle = $("#togBazz").val();
            var bazz = $('input[name=bazz]').val();
            //Prevent bazz input from sending to server when toggled off
            if (bazzToggle === false && bazz !== null) {
                clearBazz();
            }
            // break out of function and return feedback on empty inputs.
            if (start && end && fizz && buzz && (!bazzToggle || (bazzToggle && bazz))) {
                try {
                    //Round decimals to the nearest integer
                    start = Math.round(start);
                    end = Math.round(end);
                    fizz = Math.round(fizz);
                    buzz = Math.round(buzz);
                    if (bazz) {
                        bazz = Math.round(bazz);
                    }
                    var formData = form.serialize();
                } catch (error) {
                    //print out the error and break out
                    $("#output").html(error);
                    return false;
                }
                //alert(formData);
                $.ajax({
                    url: '@Url.Action("FizzBuzzBazz", "FizzleBizzle")',
                    type: "POST",
                    data: formData
                }).done(function (result) {
                    $("#output").html(result);
                }).fail(function () {
                    $("#output").html("There were invalid inputs.");
                });
            }
            else if (!start) {
                showError($('input[name=start]'));
            }
            else if (!end) {
                showError($('input[name=end]'));
            }
            else if (!fizz) {
                showError($('input[name=fizz]'));
            }
            else if (!buzz) {
                showError($('input[name=buzz]'));
            }
            else if (bazzToggle && !bazz) {
                showError($('input[name=bazz]'));
            }
            return false;
        });
    })
    $(function () {
        $(".bazz").hide();
        $("#togBazz").bootstrapToggle();
        $("#togBazz").change(function () {
            if ($(this).prop('checked')) {
                $(".bazz").show();
            } else {
                $(".bazz").hide();
                clearBazz();
            }
        })
    });

    function clearBazz() {
        $("input[name=bazz]").val(null);
        $("input[name=type]").val(null);
    }
    function showError(element) {
        element.style.border = "red 3px solid";
        element.focus();
    }
</script>

FizzleBizzle/Views/FizzleBizzle/Index.cshtml
@model FizzleBizzleModel
@{
    Page.Title = "FizzleBizzleTest";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="col-xs-12 fb-content">
    <section class="clearfix">
        <h1>Fizzle Bizzle Test</h1>
        <hr />
        <h4 class="float-right" style="margin-top:3px;">For Engagency</h4>
    </section>
    <section>
        <p>
            <b>FizzBuzz</b> generates an array of strings representing the consecutive sequence of integers from start to end.
            When the integer is a multiple of Fizz, the string "Fizz" will be added instead. Likewise, for multiples of Buzz,
            "Buzz" is added. For multiples of both Fizz and Buzz, "FizzBuzz" is added.
        </p>
        <div class="fb-example">
            <h4>For example:</h4>
            <p>
                With Fizz = 3, Buzz = 5, start = 1, and end = 15; the array looks like:<br />
                ["1","2","Fizz","4","Buzz","Fizz","7","8", ... ,"14","FizzBuzz"]
            </p>
        </div>
    </section>
    <section class="clearfix">
        @Html.Partial("FizzBuzzBazz")
    </section>
    @Html.Partial("Results")
</div>
<script>
    
</script>

FizzleBizzle/Views/FizzleBizzle/Results.cshtml
<div id="output"> Output:<br />
    @if(ViewBag.Result != null){
        for (int i = 0; i < ViewBag.Result.Length; i++)
        {
            <span>
                @ViewBag.Result[i];
            </span>
        }
    }
</div>

FizzleBizzle/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
    <head>
        <title>@Page.Title</title>
        @*<link href="~/Content/bootstrap-theme.css" rel="stylesheet" />*@
        <link href="~/Content/bootstrap-theme.min.css" rel="stylesheet" />
        @*<link href="~/Content/bootstrap.css" rel="stylesheet" />*@
        <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
        <link href="~/Content/FizzleBizzle.css" rel="stylesheet" />
        <link href="https://gitcdn.github.io/bootstrap-toggle/2.2.2/css/bootstrap-toggle.min.css" rel="stylesheet">
        @*<script src="~/Scripts/jquery-3.1.1.js"></script>*@
        <script src="~/Scripts/jquery-3.1.1.min.js"></script>
        @*<script src="~/Scripts/bootstrap.js"></script>*@
        <script src="~/Scripts/bootstrap.min.js"></script>
        <script src="https://gitcdn.github.io/bootstrap-toggle/2.2.2/js/bootstrap-toggle.min.js"></script>
    </head>
    <body>
        @RenderBody()
    </body>
</html>